from enum import Enum

class PaymentState(Enum):
    Pending = "Pending"
    Authorized = "Authorized"
    Refused = "Refused"
    Unknown = "Unknown"
    Registered = "Registered"
    Error = "Error"
    Refunded = "Refunded"
    Refunding = "Refunding"
    Waiting = "Waiting"
    Canceled = "Canceled"
    Contested = "Contested"
    WaitingBankValidation = "WaitingBankValidation"
    WaitingBankWithdraw = "WaitingBankWithdraw"
    Abandoned = "Abandoned"
    WaitingAuthentication = "WaitingAuthentication"
    AuthorizedPreprod = "AuthorizedPreprod"
    Corrected = "Corrected"
    Deleted = "Deleted"
    Inconsistent = "Inconsistent"
    NoDonation = "NoDonation"
    Init = "Init"